[package]
name = "tre"
version = "0.1.0"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"

[dependencies]
codespan = "0.9.4"
codespan-reporting = "0.9.4"
lasso = "0.2.2"
lexical = "5.2.0"
rustyline = "6.2.0"
rustyline-derive = "0.3.1"
ansi_term = "0.12.1"
